[WIP] Journalist can create article
CraftAcademy/client_admin_el_gaucho_nyheter pull request #3
Opened 2020-10-11 16:54 UTC by mauroavellaneda

[PT](https://www.pivotaltracker.com/story/show/175137722)
## This PR contains:
- Acceptance tests
- Login package
- 'Create Article' button

2020-10-12 14:55 UTC, emiliano-ma approved these changes

2020-10-12 15:01 UTC, oliverochman requested changes

2020-10-12 15:01 UTC, oliverochman commented on cypress/integration/journalistCanLoginAndSeeCreateButton.feature.js
> +      // cy.get('[data-cy="message"]').should("contain", "Welcome journalist@mail.com");
remove commented out code

2020-10-12 15:01 UTC, oliverochman commented on cypress/integration/journalistCanLoginAndSeeCreateButton.feature.js
> +      // cy.get('[data-cy="message"]').should("contain", "Invalid credentials");
this is a message you should display

2020-10-12 15:01 UTC, oliverochman commented on src/components/Header.jsx
> +  // const { role } = useParams();
remove commented out code

2020-10-12 15:01 UTC, oliverochman commented on src/modules/createForm.js
> +const createForm = async (props) => {
go ahead with the same module structure we used on the user fronting client

Articles.create()

2020-10-13 07:19 UTC, oliverochman requested changes

2020-10-13 07:19 UTC, oliverochman commented on cypress/integration/journalistCanCreateArticle.feature.js
> +      cy.get('[data-cy="content"]').type("Content");
is the content input outside of the form?

2020-10-13 07:19 UTC, oliverochman commented on cypress/integration/journalistCanLoginAndSeeCreateButton.feature.js
> +      });
please add a test to see error response

2020-10-13 07:19 UTC, oliverochman commented on cypress/integration/journalistCanLoginAndSeeCreateButton.feature.js
> +    it("invalid credentials", () => {
what happens if a user that does not have the role of journalist log in?

2020-10-13 07:19 UTC, oliverochman commented on src/modules/createForm.js
> +        "/journalist/articles",
do you have the journalist namespace on the backend?

2020-10-14 15:51 UTC, SebastianN97 approved these changes

2020-10-15 11:48 UTC, emtalen requested changes

2020-10-15 11:48 UTC, emtalen commented on src/App.jsx
> +  }
Can you please an else here, what should happen if the logged in user is not a journalist? Can we redirect to a page that indicates for the registered user that he or she is in the wrong place?

2020-10-15 13:03 UTC, merged